# This is a basic workflow to help you get started with Actions

name: GitHub wiki 

on:
  push:
    branches:
      - main

jobs:
  job1:
    name: build
    runs-on: ubuntu-latest
    steps:
      - run: echo job1 build

  job2:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo job2 deploy


