# This is a basic workflow to help you get started with Actions

name: GitHub wiki 

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      #- name: build
      - run: echo Job1
  job2:
    runs-on: ubuntu-latest
    steps:
      #- name: deploy
      - run: echo Job2
