# This is a basic workflow to help you get started with Actions

name: GitHub wiki 

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - name: build
  job2:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - name: deploy
