# This is a basic workflow to help you get started with Actions

name: GitHub wiki 

on:
  push:
    branches:
      - main

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo job1 run

  job2:
    name: job2
    runs-on: ubuntu-latest
    steps:
      - run: echo job2 run


